# This file was generated by GoReleaser. DO NOT EDIT.
cask "cartographer" do
  version "2.2.0"

  on_macos do
    on_intel do
      sha256 "af86fe87a7e0962670fe7ec062b5ceda101b9225c9f7267007c05c705c35fe3b"
      url "https://github.com/BeppeTemp/cartographer/releases/download/v#{version}/cartographer-darwin-amd64"
      binary "cartographer-darwin-amd64", target: "cartographer"
    end
    on_arm do
      sha256 "a014494543c317e864b874aed4df3aec311f024fcf0f95f87fb322e1e292e770"
      url "https://github.com/BeppeTemp/cartographer/releases/download/v#{version}/cartographer-darwin-arm64"
      binary "cartographer-darwin-arm64", target: "cartographer"
    end
  end

  on_linux do
    on_intel do
      sha256 "673f3d58985dc0e24306232fb9609ed788ac05934df120207b4d4f2bbfdbec3b"
      url "https://github.com/BeppeTemp/cartographer/releases/download/v#{version}/cartographer-linux-amd64"
      binary "cartographer-linux-amd64", target: "cartographer"
    end
    on_arm do
      sha256 "2578100c28d31a9c663abfabd0bf68cf03570c81168233858bd7fcfc16be5a00"
      url "https://github.com/BeppeTemp/cartographer/releases/download/v#{version}/cartographer-linux-arm64"
      binary "cartographer-linux-arm64", target: "cartographer"
    end
  end

  name "cartographer"
  desc "MCP governance server for the Agentic Wiki — persistent, git-backed knowledge bases for LLM agents"
  homepage "https://github.com/BeppeTemp/cartographer"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}"]
    end
  end

  # No zap stanza required

end
