# This file was generated by GoReleaser. DO NOT EDIT.
cask "cartographer" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}"]
    end
  end

  version "0.20.0"

  on_macos do
    on_arm do
      sha256 "cad99fb4efa4bfd50dabeba608267e0d7ba7684f6185abf6dfdc930b7fd491ef"
      url "https://github.com/BeppeTemp/cartographer/releases/download/v#{version}/cartographer-darwin-arm64"
      binary "cartographer-darwin-arm64", target: "cartographer"
    end
    on_intel do
      sha256 "b8c8fa70200738e76ec6ca128c37c35f6ee74e72bab86de56525fd08ef2ce40f"
      url "https://github.com/BeppeTemp/cartographer/releases/download/v#{version}/cartographer-darwin-amd64"
      binary "cartographer-darwin-amd64", target: "cartographer"
    end
  end
  on_linux do
    on_arm do
      sha256 "ca97cc77975d484fa53f4df744fbe9d9f745e4fd889f921d39b3566c431b93ca"
      url "https://github.com/BeppeTemp/cartographer/releases/download/v#{version}/cartographer-linux-arm64"
      binary "cartographer-linux-arm64", target: "cartographer"
    end
    on_intel do
      sha256 "0c666c13080eb9192fa451ec670f05592a958c337b3db38c96d18e66f6a7d697"
      url "https://github.com/BeppeTemp/cartographer/releases/download/v#{version}/cartographer-linux-amd64"
      binary "cartographer-linux-amd64", target: "cartographer"
    end
  end

  name "cartographer"
  desc "MCP governance server for the Agentic Wiki — persistent, git-backed knowledge bases for LLM agents"
  homepage "https://github.com/BeppeTemp/cartographer"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

  caveats <<~EOS
    First install: cartographer setup   (server, first knowledge base and agents, in one guided step)
    Upgrade:       nothing to do — the next cartographer sync switches the service to the new binary; cartographer upgrade-repair does it now
  EOS
end
