# This file was generated by GoReleaser. DO NOT EDIT.
cask "cartographer" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}"]
    end
  end

  version "0.19.1"

  on_macos do
    on_arm do
      sha256 "20035f0ba1cacfd30c6f375d5d3d0adf4c36aa1157b139d891973208b085c26a"
      url "https://github.com/BeppeTemp/cartographer/releases/download/v#{version}/cartographer-darwin-arm64"
      binary "cartographer-darwin-arm64", target: "cartographer"
    end
    on_intel do
      sha256 "d8242045d5a129f8ec49696c9234d02a936ae4dac352edf46e22e78c9c4d785e"
      url "https://github.com/BeppeTemp/cartographer/releases/download/v#{version}/cartographer-darwin-amd64"
      binary "cartographer-darwin-amd64", target: "cartographer"
    end
  end
  on_linux do
    on_arm do
      sha256 "8b2ab9755dee9d4e08cbfaf3d19f6bcbecce1dcb77aada85f1790cc6ec0c1465"
      url "https://github.com/BeppeTemp/cartographer/releases/download/v#{version}/cartographer-linux-arm64"
      binary "cartographer-linux-arm64", target: "cartographer"
    end
    on_intel do
      sha256 "62915a77d433fa798d1b90979144ae5ba3ba6bf33f3cfd5d1d600477c6d6bf4c"
      url "https://github.com/BeppeTemp/cartographer/releases/download/v#{version}/cartographer-linux-amd64"
      binary "cartographer-linux-amd64", target: "cartographer"
    end
  end

  name "cartographer"
  desc "MCP governance server for the Agentic Wiki — persistent, git-backed knowledge bases for LLM agents"
  homepage "https://github.com/BeppeTemp/cartographer"

  livecheck do
    skip "Auto-generated on release."
  end

  # No zap stanza required

  caveats <<~EOS
    First install: cartographer setup   (server, first knowledge base and agents, in one guided step)
    Upgrade:       nothing to do — the next cartographer sync switches the service to the new binary; cartographer upgrade-repair does it now
  EOS
end
